### ISSUE TITLE
请教：发送文件接口，微信崩溃

### ISSUE THREAD

**Issue by sjpanysys746** [holdyeah/wechat-pc-hook-python#9]
博主，请教一下，发送文件的接口一调用微信就崩溃，发送普通文本消息和接收消息都没问题。

**Comment by holdyeah** [comment]
> 博主，请教一下，发送文件的接口一调用微信就崩溃，发送普通文本消息和接收消息都没问题。

您好，发文件的接口调用需要您有一个文件（不包括图片）及文件地址。
不知道能不能帮助您
